ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB1
AVR_TOOLS_DIR = /usr
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/cores/arduino
BOARDS_TXT = /usr/share/arduino/hardware/arduino/boards.txt
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/variants
BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders


BOARD_TAG    = nano328
ARDUINO_LIBS =

include /usr/share/arduino/Arduino.mk
